---
title: "Loan Prediction"
author: "Naomi Ng’ang'a"
date: "7/24/2018"
output: html_document
---


```{r setup, include=FALSE}
#Setting working directory

basedir <- "/Users/busarauser/Box Sync/box_sync/self_learning/Kaggle_competition/loan_prediction"
knitr::opts_knit$set(root.dir = basedir)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
knitr::opts_chunk$set(error = TRUE)

#* Clear all data from memory 
 # rm(list = ls())
  

# load required package
pkgs <- c("readxl", "dplyr", "tidyverse","ggplot2","caret","kernlab","ROCR","class",
          "mice", "lubridate", "tidyr","factoextra","Hmisc","DMwR","caret","randomForest")

#if(!"pacman" %in% installed.package_cats()[,1]){install.package_cats("pacman")}
pacman::p_load(pkgs, character.only = T, install = T)

options(scipen = 999)

```


#reading in data

```{r}

train<-read.csv("./data/train.csv",stringsAsFactors = F)

test<-read.csv("./data/test.csv",stringsAsFactors = F)

#combine the data set
full_data <- plyr::rbind.fill(train, test)
```

#Data Cleaning

```{r}
#check data structure

str(full_data)
full_data<-full_data%>%
  mutate(Loan_Status=ifelse(Loan_Status=="Y",1,0))%>%
  mutate(Loan_Status=factor(Loan_Status,levels=c(0:1),labels=c("No","Yes")))


```

#check for missingness in data

```{r}

#check for pattern or missing values in data.

missingnes<-apply(full_data, 2, function(col)sum(is.na(col) |col=="")/length(col)*100)
missingnes
```

```{r}
##change categorical varibales to factor

listvars=c("Gender","Married","Dependents","Self_Employed")

for(i in listvars){
 full_data[,i] <-ifelse(full_data[,i] =="",NA,full_data[,i])
  full_data[,i] <-as.factor(full_data[,i])
 
}

#Impute missing variables

library(mice)
miceMod <- mice(full_data[, !names(full_data) %in% "Loan_Status"], method="rf")

clean_full_data<- complete(miceMod)

#merge to get response variable
full_data<-full_data%>%
  dplyr::select(Loan_ID,Loan_Status)

Clean_full_data<-merge(clean_full_data,full_data,by="Loan_ID")


listvars=c("Gender","Married","Dependents","Self_Employed","Property_Area","Education")

for(i in listvars){
  Clean_full_data[,i] <-as.factor(Clean_full_data[,i])
 
}


```


#divide data into train and test for modelling


```{r}
Clean_full_data<-Clean_full_data%>%
  ungroup%>%
  arrange(Loan_Status)

#divide data into train and test
model_train <- Clean_full_data[1:nrow(train),]
model_test <- Clean_full_data[-(1:nrow(train)),]

#extract test loan ids
sample<-data.frame(model_test$Loan_ID)


#drop loan ids from both train and test data
model_train<-model_train%>%dplyr::select(-Loan_ID)

model_test<-model_test%>%dplyr::select(-Loan_ID)

```


#Random forest

```{r}

#Find the best number of nodes to split on at each level

#control <- trainControl(method="repeatedcv", number=10, repeats=3, search="random")

#set.seed(20)
#mtry <- sqrt(ncol(model_train))
 
#tunegrid <- expand.grid(.mtry=mtry)
 
#rf_random <- train(Loan_Status ~ ., data=model_train, method="rf", metric="Accuracy", tuneLength=15, trControl=control)

# print(rf_random)

#run random forest
rf_model<-randomForest(Loan_Status ~ ., data=model_train,type=classification, ntree=4000,mtry=2)

#make prediction on test data

rf.prediction = predict(rf_model,model_test)

#check accuracy

```



#Export predictions 

```{r}

finalsub_R_F <-sample%>%
  mutate(Loan_Status=rf.prediction)

write.csv(finalsub_R_F,"./output/RF_submission1.csv",row.names = F)

```

